// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlVoP74Qy38aeOuffY6BAtEtBtCqpkNCw',
    appId: '1:979669520778:web:0c3cf55d0331bac6b9b873',
    messagingSenderId: '979669520778',
    projectId: 'chat-app-17b92',
    authDomain: 'chat-app-17b92.firebaseapp.com',
    storageBucket: 'chat-app-17b92.appspot.com',
    measurementId: 'G-054XRD35RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyqFm1jE6BvNMPeEPopqM4gV7jUUQe4c',
    appId: '1:979669520778:android:7b5a7d150b67730cb9b873',
    messagingSenderId: '979669520778',
    projectId: 'chat-app-17b92',
    storageBucket: 'chat-app-17b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAijUK0zHnywLrgEiWAtHOyyU2QlhWv_so',
    appId: '1:979669520778:ios:ea759d749e745612b9b873',
    messagingSenderId: '979669520778',
    projectId: 'chat-app-17b92',
    storageBucket: 'chat-app-17b92.appspot.com',
    iosClientId: '979669520778-cakvsbase0fju98smdqnfu49h85v37dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
